# **TASK 1**

In [2]:
from google.colab import files
uploaded = files.upload()

Saving orders.csv to orders.csv

In [4]:
import pandas as pd
df=pd.read_csv("orders.csv",index_col="order_id")
df

,customer_name,product,quantity,unit_price,order_date,status
order_id,,,,,,
1001,Alice Johnson,Laptop,1.0,85000.0,2024-01-15,delivered
1002,Bob Smith,Mouse,3.0,499.0,2024-01-16,pending
1003,Carol White,Monitor,2.0,15000.0,NaN,delivered
1004,Dave Brown,Keyboard,NaN,1200.0,2024-01-18,cancelled
1005,Eva Green,Laptop,1.0,85000.0,2024-01-19,delivered
1006,Frank Miller,USB Hub,5.0,799.0,2024-01-20,pending
1007,Grace Lee,Webcam,NaN,2500.0,2024-01-21,delivered
1008,Henry Wilson,Monitor,1.0,14500.0,NaN,pending
1009,Isla Thomas,Mouse,2.0,499.0,2024-01-23,cancelled
1010,Jack Moore,Headphones,3.0,3999.0,2024-01-24,delivered
1011,Karen Hall,Keyboard,2.0,1200.0,2024-01-25,pending
1012,Leo Adams,Laptop,NaN,85000.0,2024-01-26,delivered
1013,Mia Scott,USB Hub,4.0,799.0,NaN,pending
1014,Noah Carter,Webcam,1.0,2500.0,2024-01-28,cancelled
1015,Olivia Evans,Headphones,2.0,3999.0,2024-01-29,delivered
1016,Paul Harris,Mouse,6.0,499.0,2024-01-30,pending
1017,Quinn Martin,Monitor,NaN,14500.0,2024-01-31,delivered
1018,Rachel King,Laptop,1.0,85000.0,NaN,delivered
1019,Sam Wright,Keyboard,3.0,1200.0,2024-02-01,cancelled
1020,Tina Baker,USB Hub,2.0,799.0,2024-02-02,pending

In [5]:
first_five=df.head()
first_five

          customer_name   product  quantity  unit_price  order_date     status
order_id
1001      Alice Johnson    Laptop       1.0     85000.0  2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0  2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0         NaN  delivered
1004         Dave Brown  Keyboard       NaN      1200.0  2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0  2024-01-19  delivered

In [6]:
last_five=df.tail()
last_five

         customer_name   product  quantity  unit_price  order_date     status
order_id
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Keyboard       3.0      1200.0  2024-02-01  cancelled
1020        Tina Baker   USB Hub       2.0       799.0  2024-02-02    pending

# **TASK 2**

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

In [17]:
rows_columns=df.shape
print("Rows&Columns:",rows_columns)

Rows&Columns: (20, 6)

In [12]:
missing_values=df.isnull().sum()
missing_values

customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

In [18]:
df['order_date']=pd.to_datetime(df['order_date'])
df

,customer_name,product,quantity,unit_price,order_date,status
order_id,,,,,,
1001,Alice Johnson,Laptop,1.0,85000.0,2024-01-15,delivered
1002,Bob Smith,Mouse,3.0,499.0,2024-01-16,pending
1003,Carol White,Monitor,2.0,15000.0,NaT,delivered
1004,Dave Brown,Keyboard,NaN,1200.0,2024-01-18,cancelled
1005,Eva Green,Laptop,1.0,85000.0,2024-01-19,delivered
1006,Frank Miller,USB Hub,5.0,799.0,2024-01-20,pending
1007,Grace Lee,Webcam,NaN,2500.0,2024-01-21,delivered
1008,Henry Wilson,Monitor,1.0,14500.0,NaT,pending
1009,Isla Thomas,Mouse,2.0,499.0,2024-01-23,cancelled
1010,Jack Moore,Headphones,3.0,3999.0,2024-01-24,delivered
1011,Karen Hall,Keyboard,2.0,1200.0,2024-01-25,pending
1012,Leo Adams,Laptop,NaN,85000.0,2024-01-26,delivered
1013,Mia Scott,USB Hub,4.0,799.0,NaT,pending
1014,Noah Carter,Webcam,1.0,2500.0,2024-01-28,cancelled
1015,Olivia Evans,Headphones,2.0,3999.0,2024-01-29,delivered
1016,Paul Harris,Mouse,6.0,499.0,2024-01-30,pending
1017,Quinn Martin,Monitor,NaN,14500.0,2024-01-31,delivered
1018,Rachel King,Laptop,1.0,85000.0,NaT,delivered
1019,Sam Wright,Keyboard,3.0,1200.0,2024-02-01,cancelled
1020,Tina Baker,USB Hub,2.0,799.0,2024-02-02,pending

In [20]:
'''The order_date column needs data type conversion,
and the pd.to_datetime() function should be used to convert it
 into datetime format before performing date-based analysis.'''

# **TASK 3**

In [22]:
df.describe()

        quantity    unit_price           order_date
count  16.000000     20.000000                   16
mean    2.437500  20224.600000  2024-01-24 09:00:00
min     1.000000    499.000000  2024-01-15 00:00:00
25%     1.000000    799.000000  2024-01-19 18:00:00
50%     2.000000   2500.000000  2024-01-24 12:00:00
75%     3.000000  14625.000000  2024-01-29 06:00:00
max     6.000000  85000.000000  2024-02-02 00:00:00
std     1.504161  33573.389607                  NaN

In [21]:
df['unit_price'].median()

2500.0

Median unit_price:
The median unit_price is 2500.

Is unit_price skewed?
Yes, the unit_price distribution appears to be positively (right) skewed.

Explanation:

->The maximum value (85000) is much higher than most prices.

->The median is only 2500, which is far lower than the highest values.

->A few very expensive items (like laptops) pull the distribution to the right.

This large gap between typical values and the maximum indicates right skewness.