**Import Libraries and Create Dataset**

In [2]:
import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

**Task 1: Inspect Dataset**

In [3]:
### Inspect Data
#We check the structure of the dataset and identify missing values.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

In [4]:
df.isna().sum()

transaction_id      0
date                0
region              3
product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

**Task 2: Handle Missing Values**

In [11]:
# Fill region with mode
df['region'] = df['region'].fillna(df['region'].mode()[0])
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [10]:
# Fill product_category with mode
df['product_category'] = df['product_category'].fillna(df['product_category'].mode()[0])
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [9]:
# Fill sales_amount with median
df['sales_amount'] = df['sales_amount'].fillna(df['sales_amount'].median())
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [8]:
 # Forward fill quantity
df.loc[:, 'quantity'] = df['quantity'].ffill()
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,2024-10-08,North,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [ ]:
# Fill customer_age with mean (rounded)
df.loc[:, 'customer_age'] = df['customer_age'].fillna(round(df['customer_age'].mean()))
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,36.0,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,36.0,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,36.0,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,36.0,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI

In [ ]:
# Drop rows where payment_method is missing
df = df.dropna(subset=['payment_method'])
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI

In [ ]:
# Verify missing values
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

**Task 3: GroupBy Analysis**

We analyze the dataset using groupby operations to understand sales distribution.

In [12]:
#Calculate total Sales by Region
sales_by_region = df.groupby('region')['sales_amount'].sum()
sales_by_region

region
East     3790.0
North    6800.0
South    2540.0
West     4030.0
Name: sales_amount, dtype: float64

In [13]:
#Calculate average sales by product_category
avg_sales_category = df.groupby('product_category')['sales_amount'].mean()
avg_sales_category

product_category
Books           466.250000
Clothing        674.285714
Electronics    1465.000000
Home            812.500000
Name: sales_amount, dtype: float64

In [14]:
#Sales & Quantity by Region and Product Category
region_product_sales = df.groupby(['region','product_category'])[['sales_amount','quantity']].sum().reset_index()
region_product_sales

   region product_category  sales_amount  quantity
0    East            Books         800.0       4.0
1    East         Clothing         890.0       3.0
2    East      Electronics        2100.0       1.0
3   North            Books         340.0       3.0
4   North         Clothing         510.0       3.0
5   North      Electronics        2700.0       3.0
6   North             Home        3250.0      12.0
7   South         Clothing        2540.0      13.0
8    West            Books         725.0       1.0
9    West         Clothing         780.0       5.0
10   West      Electronics        2525.0       2.0

In [15]:
#Display top 3 region-product combinations by sales
top3 = region_product_sales.sort_values(by='sales_amount', ascending=False).head(3)
top3

  region product_category  sales_amount  quantity
6  North             Home        3250.0      12.0
5  North      Electronics        2700.0       3.0
7  South         Clothing        2540.0      13.0

**Task 4: Custom Aggregation**

We create a custom function to calculate the sales range and apply multiple aggregations using agg().

In [16]:
#Sales Range Function
def sales_range(x):
    return x.max() - x.min()

In [17]:
#Apply Sales Range by Region
sales_range_region = df.groupby('region')['sales_amount'].apply(sales_range)
sales_range_region

region
East     1720.0
North    1160.0
South     275.0
West     1075.0
Name: sales_amount, dtype: float64

In [18]:
#Multiple Aggregations
agg_results = df.groupby('region').agg({
    'sales_amount':['sum','mean','max'],
    'quantity':['sum','min']
})

agg_results

       sales_amount                 quantity
                sum    mean     max      sum  min
region
East         3790.0   947.5  2100.0      8.0  1.0
North        6800.0   850.0  1500.0     21.0  1.0
South        2540.0   635.0   725.0     13.0  2.0
West         4030.0  1007.5  1800.0      8.0  1.0